#!/usr/bin/env bash
# Version: v.22.05.30

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
ODOO_WORK_DIR="$(cd "${SCRIPT_PATH}/../.." && /bin/pwd)"
. "${ODOO_WORK_DIR}/.env-default" && \
. "${ODOO_WORK_DIR}/.env-shared" && \
. "${ODOO_WORK_DIR}/.env-secret"
cd "${ODOO_WORK_DIR}"

if [ "${ODOO_UNACCENT}" == true ]; then
    result="$(/usr/bin/psql -qc 'CREATE EXTENSION IF NOT EXISTS unaccent' 2>&1)"
    ok="${?}"
    if [ "${ok}" -eq 0 -a -z "${result}" ]; then
        log INFO Unaccent extension installed
    elif [ "${ok}" -ne 0 ]; then
        log WARNING Attempt to install unaccent in "${PGDATABASE}@${PGHOST}" failed with this message: "${result}"
    fi
fi
