#!/usr/bin/env bash
export OPENERP_SERVER="$ODOO_WORK_DIR/auto/odoo.conf"
if [ -f  "${OPENERP_SERVER}" ]; then
    log INFO File $OPENERP_SERVER exists, skipping config generation
    exit 0
fi

config-generate
