#!/bin/sh

set -e

SCRIPT_PATH=$(cd "$(/usr/bin/dirname "$0")" && /bin/pwd)
ODOO_WORK_DIR=$(cd $SCRIPT_PATH/.. && /bin/pwd)
cd $ODOO_WORK_DIR

if [ -z "$LIBRARIES_VERSION_BRANCH" ]; then
  if [ "$(/usr/bin/sha1sum $ODOO_WORK_DIR/bootstrap | /usr/bin/awk '{ print $1}')" = "7b53eaced73cc36675859da32bdfb6c2c1c428fe" ] || [ "$(/usr/bin/sha1sum $ODOO_WORK_DIR/bootstrap | /usr/bin/awk '{ print $1}')" = "56f5b836e417fa9c6b1d8cdc2afe5a96c91205a5" ]; then
    /usr/bin/curl https://raw.githubusercontent.com/sunflowerit/waft/master/bootstrap -o $ODOO_WORK_DIR/bootstrap
    /bin/sed -i "s/^export LIBRARIES_VERSION_BRANCH='.*'/export LIBRARIES_VERSION_BRANCH='v.21.05.10'/gI" $ODOO_WORK_DIR/bootstrap
    $ODOO_WORK_DIR/bootstrap
    exit 0
  else
    /bin/echo "$ODOO_WORK_DIR/bootstrap files does not have 'LIBRARIES_VERSION_BRANCH' variable! update it by this command:"
    /bin/echo "  /usr/bin/curl https://raw.githubusercontent.com/sunflowerit/waft/a6d02d7215733c0ac2d32e87ee497b8653b9551f/bootstrap -o $ODOO_WORK_DIR/bootstrap"
    exit 1
  fi
fi

if [ -f $ODOO_WORK_DIR/pipenv ]; then
  rm -f $ODOO_WORK_DIR/pipenv
fi

/bin/mkdir -p $ODOO_WORK_DIR/auto/addons/
/bin/mkdir -p $ODOO_WORK_DIR/common/build.d/
/bin/mkdir -p $ODOO_WORK_DIR/common/conf.d/
/bin/mkdir -p $ODOO_WORK_DIR/common/entrypoint.d/
/bin/mkdir -p $ODOO_WORK_DIR/custom/src/private/

if [ ! -f $ODOO_WORK_DIR/.env-shared ]; then
  if [ -f $ODOO_WORK_DIR/.env-secret ]; then
    . $ODOO_WORK_DIR/.env-secret
    if [ "$ODOO_VERSION" != "" ]; then
      /bin/cp $ODOO_WORK_DIR/waftlib/templates/$ODOO_VERSION/.env-shared $ODOO_WORK_DIR/
    else
      /bin/echo "You should define 'ODOO_VERSION' variable in $ODOO_WORK_DIR/.env-secret"
      exit 1
    fi
  else
    if [ "$ODOO_VERSION" != "" ]; then
      /bin/cp $ODOO_WORK_DIR/waftlib/templates/$ODOO_VERSION/.env-shared $ODOO_WORK_DIR/
    else
      /bin/echo "Copy $ODOO_WORK_DIR/waftlib/templates/ODOO_VERSION/.env-shared to $ODOO_WORK_DIR manually"
      /bin/echo "or define 'ODOO_VERSION' variable in $ODOO_WORK_DIR/.env-secret"
      exit 1
    fi
  fi
fi

/usr/bin/touch $ODOO_WORK_DIR/.env-secret

. $ODOO_WORK_DIR/.env-shared && \
. $ODOO_WORK_DIR/.env-secret

if [ $(/bin/echo $ODOO_VERSION | /usr/bin/cut -d'.' -f1) -lt '8' ]; then
  /bin/echo "Waft does not support $ODOO_VERSION"
  exit 1
fi

if [ $(/bin/echo $ODOO_VERSION | /usr/bin/cut -d'.' -f1) -gt '14' ]; then
  /bin/echo "Waft does not support $ODOO_VERSION yet"
  exit 1
fi

if [ ! -f $ODOO_WORK_DIR/.python-version ]; then
  /bin/cp $ODOO_WORK_DIR/waftlib/templates/$ODOO_VERSION/.python-version $ODOO_WORK_DIR/
fi

if [ ! -e $ODOO_WORK_DIR/requirements.txt ]; then
  /bin/ln -sf $ODOO_WORK_DIR/waftlib/templates/$ODOO_VERSION/requirements.txt $ODOO_WORK_DIR/
fi

if [ ! -f $ODOO_WORK_DIR/common/conf.d/odoo.cfg ]; then
  /bin/cp $ODOO_WORK_DIR/waftlib/templates/$ODOO_VERSION/odoo.cfg $ODOO_WORK_DIR/common/conf.d/
fi

if [ ! -f $ODOO_WORK_DIR/custom/src/repos.yaml ]; then
  /bin/cp $ODOO_WORK_DIR/waftlib/templates/$ODOO_VERSION/repos.yaml $ODOO_WORK_DIR/custom/src/
fi

if [ ! -f $ODOO_WORK_DIR/custom/src/addons.yaml ]; then
  /bin/cp $ODOO_WORK_DIR/waftlib/templates/$ODOO_VERSION/addons.yaml $ODOO_WORK_DIR/custom/src/
fi

if [ ! -f "$ODOO_WORK_DIR/.python-version" ]; then
  /bin/echo "You should create .python-version variable in $ODOO_WORK_DIR"
  exit 1
fi

if [ ! -d $ODOO_WORK_DIR/.pyenv ]; then
  /usr/bin/git clone https://github.com/pyenv/pyenv $ODOO_WORK_DIR/.pyenv
fi

VIRTUALENV=$ODOO_WORK_DIR/.pyenv/bin/virtualenv.pyz
if [ ! -f $VIRTUALENV ]; then
wget https://bootstrap.pypa.io/virtualenv.pyz -O $VIRTUALENV
fi

PYENV_ROOT=$ODOO_WORK_DIR/.pyenv
PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
PYENV=$PYENV_ROOT/bin/pyenv

eval "$($PYENV init -)"

pyenv install -s

if [ ! -d $ODOO_WORK_DIR/.venv ]; then
  python $VIRTUALENV .venv
fi

# in .gitignore so not overridable
cd $ODOO_WORK_DIR/.venv/lib/*/site-packages && \
/bin/mkdir -p waftlib && \
cd waftlib && \
for f in ../../../../../waftlib/waftlib/*; do /bin/ln -sf $f; done

cd $ODOO_WORK_DIR/.venv/bin && \
for f in ../../waftlib/bin/*; do /bin/ln -sf $f; done
/bin/rm -fr $ODOO_WORK_DIR/.venv/bin/direxec

# not in .gitignore so overridable
cd $ODOO_WORK_DIR/common && \
[ ! -e build ] && /bin/ln -sf ../waftlib/bin/direxec build && \
[ ! -e entrypoint ] && /bin/ln -sf ../waftlib/bin/direxec entrypoint

cd $ODOO_WORK_DIR/common/build.d && \
for f in ../../waftlib/build.d/*; do [ ! -e $(/usr/bin/basename $f) ] && /bin/ln -sf $f $(/usr/bin/basename $f); done

cd $ODOO_WORK_DIR/common/entrypoint.d && \
for f in ../../waftlib/entrypoint.d/*; do [ ! -e $(/usr/bin/basename $f) ] && /bin/ln -sf $f $(/usr/bin/basename $f); done

cd $ODOO_WORK_DIR && [ ! -e build ] && /bin/ln -sf waftlib/build
cd $ODOO_WORK_DIR && [ ! -e initial-database ] && /bin/ln -sf waftlib/initial-database
cd $ODOO_WORK_DIR && [ ! -e install ] && /bin/ln -sf waftlib/install
cd $ODOO_WORK_DIR && [ ! -e upgrade ] && /bin/ln -sf waftlib/upgrade
cd $ODOO_WORK_DIR && [ ! -e run ] && /bin/ln -sf waftlib/run
cd $ODOO_WORK_DIR && [ ! -e shell ] && /bin/ln -sf waftlib/shell
cd $ODOO_WORK_DIR && [ ! -e migrate ] && /bin/ln -sf waftlib/migrate
cd $ODOO_WORK_DIR && [ ! -e odoo-service ] && /bin/ln -sf waftlib/odoo-service

# set permissions
/bin/chmod 750 $ODOO_WORK_DIR || true
/bin/chmod 750 $ODOO_WORK_DIR/auto || true
/bin/chmod 750 $ODOO_WORK_DIR/auto/addons || true
/bin/chmod 750 $ODOO_WORK_DIR/waftlib/bin || true
/bin/chmod 750 $ODOO_WORK_DIR/waftlib/build || true
/bin/chmod 750 $ODOO_WORK_DIR/waftlib/run || true
/bin/chmod 750 $ODOO_WORK_DIR/waftlib/install || true
/bin/chmod 750 $ODOO_WORK_DIR/waftlib/upgrade || true
/bin/chmod 750 $ODOO_WORK_DIR/waftlib/shell || true
/bin/chmod 750 $ODOO_WORK_DIR/waftlib/migrate || true
/bin/chmod 750 $ODOO_WORK_DIR/waftlib/initial-database || true
/bin/chmod 750 $ODOO_WORK_DIR/waftlib/odoo-service || true
/bin/chmod 740 $ODOO_WORK_DIR/waftlib/bin/* || true
/bin/chmod 750 $ODOO_WORK_DIR/common || true
/bin/chmod 750 $ODOO_WORK_DIR/common/build.d || true
/bin/chmod 740 $ODOO_WORK_DIR/common/build.d/* || true
/bin/chmod 750 $ODOO_WORK_DIR/common/conf.d || true
/bin/chmod -f 640 $ODOO_WORK_DIR/common/conf.d/odoo.cfg || true
/bin/chmod 750 $ODOO_WORK_DIR/common/entrypoint.d || true
/bin/chmod 740 $ODOO_WORK_DIR/common/entrypoint.d/* || true
/bin/chmod 750 $ODOO_WORK_DIR/custom || true
/bin/chmod 750 $ODOO_WORK_DIR/custom/src || true
/bin/chmod 750 $ODOO_WORK_DIR/custom/src/private/ || true
/bin/chmod -f 640 $ODOO_WORK_DIR/custom/src/addons.yaml || true
/bin/chmod -f 640 $ODOO_WORK_DIR/custom/src/repos.yaml || true
/bin/chmod 750 $ODOO_WORK_DIR/waftlib/waftlib || true
/bin/chmod 740 $ODOO_WORK_DIR/waftlib/waftlib/* || true
/bin/chmod 640 $ODOO_WORK_DIR/waftlib/templates/* || true
/bin/chmod 740 $ODOO_WORK_DIR/waftlib/templates/*.0 || true
/bin/chmod 640 $ODOO_WORK_DIR/waftlib/templates/*/* || true
/bin/chmod -f 600 $ODOO_WORK_DIR/.env-shared || true
/bin/chmod -f 600 $ODOO_WORK_DIR/.env-secret || true
/bin/chmod 740 $ODOO_WORK_DIR/bootstrap || true
/bin/chmod 740 $ODOO_WORK_DIR/build || true
/bin/chmod 740 $ODOO_WORK_DIR/initial-database || true
/bin/chmod 740 $ODOO_WORK_DIR/install || true
/bin/chmod 740 $ODOO_WORK_DIR/run || true
/bin/chmod 740 $ODOO_WORK_DIR/odoo-service || true
