#!/bin/sh

SCRIPT_PATH=$(cd "$(/usr/bin/dirname "$0")" && /bin/pwd)
ODOO_WORK_DIR=$SCRIPT_PATH
. $SCRIPT_PATH/.env-shared && \
. $SCRIPT_PATH/.env-secret
cd $ODOO_WORK_DIR

if [ $(id -u) -eq 0 ]; then
  echo "Please dont use sudo command with script"
  exit 1
fi

#rm -fr ./auto/odoo.conf
#rm -fr ./auto/addons/*
#/bin/bash -c "$(/bin/ls -1 ./custom/src | grep -Ev 'private|repos.yaml|addons.yaml' | /usr/bin/awk '{print("rm -fr ./custom/src/" $1)}')"

if [ ! -d $ODOO_WORK_DIR/.venv ]; then
    /bin/echo 'run ./bootstrap first!'
    exit 1
fi

# pip 20.3+ will not cache packages installed from git
. .venv/bin/activate && \
pip install "setuptools<58" && \
pip install "pip<20.3" && \
pip install -r requirements.txt && \
./common/build && \
python $ODOO_WORK_DIR/common/entrypoint
