#!/bin/sh
set -e

SCRIPT_PATH=$(cd "$(/usr/bin/dirname "$0")" && /bin/pwd)
ODOO_WORK_DIR=$SCRIPT_PATH
. $SCRIPT_PATH/.env-shared && \
. $SCRIPT_PATH/.env-secret
cd $ODOO_WORK_DIR

if [ $# -le 1 ]; then
  echo "Installs a new empty database"
  echo "Usage: ./install databasename modulename [nodemo]"
  exit
fi

if [ "$3" == "nodemo" ]
then
   DEMO="--without-demo=1"
   echo "Without demo data"
else
   DEMO="--without-demo="
   echo "With demo data"
fi

if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$1'" )" = '1' ]
then
    echo "Database '$1' already exists. If you want to drop it: 'dropdb $1'"
    exit 1
else
    createdb "$1"
fi

cd $ODOO_WORK_DIR && $HOME/.local/bin/pipenv run odoo \
  -c ./auto/odoo.conf \
  --load-language=en_US,nl_NL \
  -i "$2" \
  -d "$1" \
  --stop-after-init \
  $DEMO
