#!/bin/bash

/usr/bin/sudo /bin/systemctl stop odoo.service || /bin/true

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
export ODOO_WORK_DIR="${SCRIPT_PATH}"
set -a
. "${ODOO_WORK_DIR}/.env-default" && \
. "${ODOO_WORK_DIR}/.env-shared" && \
. "${ODOO_WORK_DIR}/.env-secret"
set +a
#ODOO_VERSION=
#PGDATABASE=
#PGHOST=
#PGUSER=
#PGPASSWORD=
#MIGRATION_ENTERPRISE_ENABLED=
#MIGRATION_ENTERPRISE_JUMP_TO=
#MIGRATION_NO_BACKUPS=
#MIGRATION_OPEN_UPGRADE_DISABLED=
#MIGRATION_START_VERSION=
#SKIP_INITIAL_UPGRADE=
#WAFT_LOG_LEVEL=

"${ODOO_WORK_DIR}/.venv/bin/python" "${SCRIPT_PATH}/waftlib/bin/migrate.py" ${@}
