#!/bin/bash
# Version: v.22.05.30

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
ODOO_WORK_DIR="${SCRIPT_PATH}"
. "${ODOO_WORK_DIR}/.env-default" && \
. "${ODOO_WORK_DIR}/.env-shared" && \
. "${ODOO_WORK_DIR}/.env-secret"
cd "${ODOO_WORK_DIR}"

. "${ODOO_WORK_DIR}/.venv/bin/activate"

${ODOO_WORK_DIR}/.venv/bin/odoo --logfile "${ODOO_WORK_DIR}/logfile/odoo.log" -c "${ODOO_WORK_DIR}/auto/odoo.conf"
