#!/bin/sh
# Version: v.22.05.30

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
ODOO_WORK_DIR="${SCRIPT_PATH}"
. "${ODOO_WORK_DIR}/.env-default" && \
. "${ODOO_WORK_DIR}/.env-shared" && \
. "${ODOO_WORK_DIR}/.env-secret"

if [ "${#}" -eq 0 ]; then
  /bin/echo "Upgrade a module"
  /bin/echo "Usage: ./upgrade-module modulename"
  exit
fi

cd "${ODOO_WORK_DIR}" && . .venv/bin/activate && odoo -c ./auto/odoo.conf -u "${1}" --xmlrpc-port 18069 --stop-after-init --i18n-overwrite
