#!/usr/bin/env bash
# Version: v.23.08.03

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
WORK_DIRECTORY="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
. "${WORK_DIRECTORY}/config/env-default" && \
. "${WORK_DIRECTORY}/config/env-shared" && \
. "${WORK_DIRECTORY}/.env-secret" && \
cd "${WORK_DIRECTORY}"

/bin/echo "( WARNING ) '${WORK_DIRECTORY}/scripts/addons-test' script: addons-test is deprecated, use instead: addons update --test ${@}"
# Shortcut to run Odoo in addons testing mode
set -e
addons="${1}"
shift
/bin/echo "( INFO ) '${WORK_DIRECTORY}/scripts/addons-test' script: Executing Odoo in addons-test mode for addons ${addons}"
# HACK `--workers 0`: https://github.com/odoo/odoo/pull/14809
. "${WORK_DIRECTORY}/.venv/bin/activate" && \
odoo --workers 0 --test-enable --stop-after-init --update "${addons}" "${@}"
