#!/usr/bin/env bash
# Version: v.23.08.03

set -e

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
WORK_DIRECTORY="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
cd "${WORK_DIRECTORY}" && \
. "${WORK_DIRECTORY}/.venv/bin/activate" && \
"${WORK_DIRECTORY}/.python-files/addons-install"
