#!/usr/bin/env bash
# Version: v.23.08.03

set -e

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
WORK_DIRECTORY="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
. "${WORK_DIRECTORY}/config/env-default" && \
. "${WORK_DIRECTORY}/config/env-shared" && \
. "${WORK_DIRECTORY}/.env-secret" && \
cd "${WORK_DIRECTORY}" && \
. "${WORK_DIRECTORY}/.venv/bin/activate"

ODOO_MAIN_CODE_DIRECTORY="${WORK_DIRECTORY}/.ignore/code/odoo"
/bin/echo "( INFO ) '${WORK_DIRECTORY}/scripts/code-install' script: Installing Odoo from ${ODOO_MAIN_CODE_DIRECTORY} ."

# Odoo v8 dependencies could crash at install, so we don't use them
if [ "${ODOO_VERSION}" == "8.0" ] ; then
  pip install --no-cache-dir --no-deps --editable "${ODOO_MAIN_CODE_DIRECTORY}"
else
  pip install --no-cache-dir --editable "${ODOO_MAIN_CODE_DIRECTORY}"
fi

# Make version 8.0 and 9.0 have an `odoo` executable
if [ "${ODOO_VERSION}" == "8.0" -o "${ODOO_VERSION}" == "9.0" ] ; then
    /bin/rm -fr "${WORK_DIRECTORY}/.venv/bin/odoo"
    /bin/ln -s "${WORK_DIRECTORY}/.venv/bin/odoo.py" "${WORK_DIRECTORY}/.venv/bin/odoo"
fi
