#!/bin/sh
# Version: v.23.08.03

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
WORK_DIRECTORY="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
. "${WORK_DIRECTORY}/config/env-default" && \
. "${WORK_DIRECTORY}/config/env-shared" && \
. "${WORK_DIRECTORY}/.env-secret" && \
cd "${WORK_DIRECTORY}" && \
. "${WORK_DIRECTORY}/.venv/bin/activate" && \
odoo -i base -c "${WORK_DIRECTORY}/.ignore/config/odoo.conf" --without-demo=all --stop-after-init
