#!/bin/sh
# Version: v.23.08.03

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
WORK_DIRECTORY="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
. "${WORK_DIRECTORY}/config/env-default" && \
. "${WORK_DIRECTORY}/config/env-shared" && \
. "${WORK_DIRECTORY}/.env-secret"

if [ "${#}" -eq 0 ] ; then
  /bin/echo "Upgrade a module"
  /bin/echo "Usage: ${WORK_DIRECTORY}/scripts/module-upgrade modulename"
  exit
fi

cd "${WORK_DIRECTORY}" && \
. "${WORK_DIRECTORY}/.venv/bin/activate" && \
odoo -c "${WORK_DIRECTORY}/.ignore/config/odoo.conf" -u "${1}" --xmlrpc-port 18069 --stop-after-init --i18n-overwrite
