#!/bin/sh
# Version: v.23.08.03

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
ODOO_WORK_DIRECTORY="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
. "${ODOO_WORK_DIRECTORY}/config/env-default" && \
. "${ODOO_WORK_DIRECTORY}/config/env-shared" && \
. "${ODOO_WORK_DIRECTORY}/.env-secret" && \
cd "${ODOO_WORK_DIRECTORY}"

# Note: in Odoo 8.0 this requires OCA 'shell' module to be installed.
. "${ODOO_WORK_DIRECTORY}/.venv-odoo/bin/activate" && \
odoo --addons-path="${ODOO_WORK_DIRECTORY}/.ignore/auto/addons" shell -c "${ODOO_WORK_DIRECTORY}/.ignore/auto/odoo.conf" --xmlrpc-port=18080
