#!/usr/bin/env bash
# Version: v.23.08.03

set -e

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
ODOO_WORK_DIRECTORY="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
. "${ODOO_WORK_DIRECTORY}/config/env-default" && \
. "${ODOO_WORK_DIRECTORY}/config/env-shared" && \
. "${ODOO_WORK_DIRECTORY}/.env-secret" && \
cd "${ODOO_WORK_DIRECTORY}" && \
. "${ODOO_WORK_DIRECTORY}/.venv-odoo/bin/activate"

ODOO_MAIN_CODE_PATH="${ODOO_WORK_DIRECTORY}/odoo-code/odoo"
/bin/echo "( INFO ) '${ODOO_WORK_DIRECTORY}/scripts/odoo-code-install' script: Installing Odoo from ${ODOO_MAIN_CODE_PATH} ."

# Odoo v8 dependencies could crash at install, so we don't use them
if [ "${ODOO_VERSION}" == "8.0" ] ; then
  pip install --no-cache-dir --no-deps --editable "${ODOO_MAIN_CODE_PATH}"
else
  pip install --no-cache-dir --editable "${ODOO_MAIN_CODE_PATH}"
fi

# Make version 8.0 and 9.0 have an `odoo` executable
if [ "${ODOO_VERSION}" == "8.0" -o "${ODOO_VERSION}" == "9.0" ] ; then
    /bin/rm -fr "${ODOO_WORK_DIRECTORY}/.venv-odoo/bin/odoo"
    /bin/ln -s "${ODOO_WORK_DIRECTORY}/.venv-odoo/bin/odoo.py" "${ODOO_WORK_DIRECTORY}/.venv-odoo/bin/odoo"
fi
