#!/bin/bash
# Version: v.23.08.03

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
WORK_DIRECTORY="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
. "${WORK_DIRECTORY}/config/env-default" && \
. "${WORK_DIRECTORY}/config/env-shared" && \
. "${WORK_DIRECTORY}/.env-secret" && \
cd "${WORK_DIRECTORY}"

. "${WORK_DIRECTORY}/.venv/bin/activate"

export ODOO_WORKERS="${ODOO_WORKERS:-8}"
if [ "${ODOO_WORKERS}" -eq '0' ] ; then
  export ODOO_XMLRPC_PORT="${ODOO_XMLRPC_PORT:-8069}"
  export ODOO_LONGPOLLING_PORT="${ODOO_LONGPOLLING_PORT:-8072}"
  /usr/bin/socat "TCP-LISTEN:${ODOO_LONGPOLLING_PORT},reuseaddr,fork" "TCp:127.0.0.1:${ODOO_XMLRPC_PORT}" &
fi

${WORK_DIRECTORY}/.venv/bin/odoo --logfile "${WORK_DIRECTORY}/logfiles/odoo.log" -c "${WORK_DIRECTORY}/.ignore/config/odoo.conf"
