#!/bin/sh
# Version: v.23.08.03

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
WORK_DIRECTORY="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
. "${WORK_DIRECTORY}/config/env-default" && \
. "${WORK_DIRECTORY}/config/env-shared" && \
. "${WORK_DIRECTORY}/.env-secret" && \
cd "${WORK_DIRECTORY}"

# Note: in Odoo 8.0 this requires OCA 'shell' module to be installed.
. "${WORK_DIRECTORY}/.venv/bin/activate" && \
odoo --addons-path="${WORK_DIRECTORY}/addons" shell -c "${WORK_DIRECTORY}/.ignore/config/odoo.conf" --xmlrpc-port=18080
