#!/usr/bin/env bash
# Version: v.23.08.03

set -e

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
ODOO_WORK_DIRECTORY="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
cd "${ODOO_WORK_DIRECTORY}"
# pip 20.3 has a neat dependency resolver
# https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020
. "${ODOO_WORK_DIRECTORY}/.venv/bin/activate" && \
pip install "setuptools<58" && \
pip install "pip>=20.3" && \
(pip uninstall --yes -r "${ODOO_WORK_DIRECTORY}/config/requirements-clean.txt" 2>/dev/null || /bin/true) && \
pip install --exists-action w -r "${ODOO_WORK_DIRECTORY}/config/requirements-install-default.txt" && \
pip install --exists-action w -r "${ODOO_WORK_DIRECTORY}/config/requirements-override-install.txt"
