#!/usr/bin/env bash
# Version: v.23.08.03

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
WORK_DIRECTORY="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
. "${WORK_DIRECTORY}/config/env-default" && \
. "${WORK_DIRECTORY}/config/env-shared" && \
. "${WORK_DIRECTORY}/.env-secret" && \
cd "${WORK_DIRECTORY}"

if [ "${WAFT_WAIT_DB,,}" != 'true' ] ; then
    /bin/echo "( WARNING ) '${WORK_DIRECTORY}/scripts/waft-database-postgresql-wait' script: Not waiting for a postgres server."
    exit 0
fi

/bin/echo "( INFO ) '${WORK_DIRECTORY}/scripts/waft-database-postgresql-wait' script: Waiting until postgres is listening at ${PGHOST}..."
while true; do
    /usr/bin/psql --list > /dev/null 2>&1 && break
    sleep 1
done
