#!/usr/bin/env bash
# Version: v.23.08.03

set -e

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
WORK_DIRECTORY="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
. "${WORK_DIRECTORY}/config/env-default" && \
. "${WORK_DIRECTORY}/config/env-shared" && \
. "${WORK_DIRECTORY}/.env-secret" && \
cd "${WORK_DIRECTORY}"

. "${WORK_DIRECTORY}/.venv/bin/activate" && \
if [ "${WAFT_COMPILE,,}" != 'true' ] ; then
    /bin/echo "( WARNING ) '${WORK_DIRECTORY}/scripts/waft-code-compile' script: Not compiling Python code"
    exit 0
fi && \
/bin/echo "( INFO ) '${WORK_DIRECTORY}/scripts/waft-code-compile' script: Compiling all Python code in ${WORK_DIRECTORY}" && \
python -m compileall -q "${WORK_DIRECTORY}/.ignore/code"
