#!/bin/sh
# Version: v.23.08.03

if [ "${#}" -le 1 ] ; then
  /bin/echo "Resets password of Odoo user"
  /bin/echo "Usage: ${0} login newpassword"
  exit
fi

USER="${1}"
NEWPASSWORD="${2}"

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
WORK_DIRECTORY="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
. "${WORK_DIRECTORY}/config/env-default" && \
. "${WORK_DIRECTORY}/config/env-shared" && \
. "${WORK_DIRECTORY}/.env-secret" && \
cd "${WORK_DIRECTORY}"

CRYPT="$(. "${WORK_DIRECTORY}/.waft-venv/bin/activate" && "${WORK_DIRECTORY}/.waft-venv/bin/python" -c "from passlib.context import CryptContext; print(CryptContext(['pbkdf2_sha512']).encrypt('${NEWPASSWORD}'))")"

COLEXISTS="$(/usr/bin/psql -XAt -d "${PGDATABASE}" -c "SELECT 1 FROM information_schema.columns WHERE table_name='res_users' AND column_name='password_crypt';")"

if [ "${COLEXISTS}" = "1" ] ; then
  /usr/bin/psql -d "${PGDATABASE}" -c "update res_users set password_crypt = '${CRYPT}', active = 't' where login = '${USER}';"
else
  /usr/bin/psql -d "${PGDATABASE}" -c "update res_users set password = '${CRYPT}', active = 't' where login = '${USER}';"
fi
