#!/usr/bin/env bash
# Version: v.23.08.03

set -e

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
WORK_DIRECTORY="$(cd "${SCRIPT_PATH}/.." && /bin/pwd)"
cd "${WORK_DIRECTORY}" && \
. "${WORK_DIRECTORY}/.waft-venv/bin/activate" && \
(pip uninstall --yes -r "${WORK_DIRECTORY}/config/waft-requirements-pre-install-default.txt" 2>/dev/null || /bin/true) && \
pip install --exists-action w -r "${WORK_DIRECTORY}/config/waft-requirements-install-default.txt"
