#!/usr/bin/env bash
set -e

if [ "$COMPILE" != true ]; then
    log WARNING Not compiling Python code
    exit 0
fi

log INFO Compiling all Python code in $ODOO_WORK_DIR
python -m compileall -q $ODOO_WORK_DIR/custom


